url: 'http://speller.yandex.net/services/spellservice?WSDL'
url_task2: 'https://test-stand.gb.ru/gateway/login'
username_task2: 'Mim#$'
password_task2: '86f17857a1'
url_post: 'https://test-stand.gb.ru/api/posts'
driver_path: 'C:\chromedriver\chromedriver.exe'
login_page: 'https://test-stand.gb.ru/login'